spring:
  datasource:
    url: jdbc:mysql://localhost:3306/letssondb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: 2967
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true





